### ISSUE TITLE
Not working on latest osx and transmit

### ISSUE THREAD

**Issue by uhlhosting** [nlemoine/transmit-2-ssh-config#1]
`
 cosmicsound  ~  t2sc -f /Users/cosmicsound/Library/Mobile\ Documents/com\~apple\~CloudDocs/Documents/t2s.transmitServers 
/usr/local/lib/node_modules/transmit-2-ssh-config/node_modules/libxmljs/lib/document.js:168
    return bindings.fromXml(string, options || {});
                    ^

Error: Start tag expected, '<' not found

    at module.exports.fromXml (/usr/local/lib/node_modules/transmit-2-ssh-config/node_modules/libxmljs/lib/document.js:168:21)
    at Command.syncFavorites [as _action] (/usr/local/lib/node_modules/transmit-2-ssh-config/dist/index.js:58:41)
    at Command._run (/usr/local/lib/node_modules/transmit-2-ssh-config/node_modules/caporal/lib/command.js:407:40)
    at Program._run (/usr/local/lib/node_modules/transmit-2-ssh-config/node_modules/caporal/lib/program.js:156:16)
    at Program.parse (/usr/local/lib/node_modules/transmit-2-ssh-config/node_modules/caporal/lib/program.js:259:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/transmit-2-ssh-config/dist/index.js:130:19)
    at Module._compile (internal/modules/cjs/loader.js:734:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
    at Module.load (internal/modules/cjs/loader.js:626:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
    at Function.Module._load (internal/modules/cjs/loader.js:558:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:797:12)
    at executeUserCode (internal/bootstrap/node.js:526:15)
    at startMainThreadExecution (internal/bootstrap/node.js:439:3)
 cosmicsound  ~  
`

**Comment by nlemoine** [comment]
Transmit changed the way they store favorites. Sadly, the script won't work for Transmit 5. 

See https://github.com/fitztrev/shuttle/issues/163#issuecomment-394274673

**Comment by nlemoine** [comment]
Hi @uhlhosting,

I found a workaround using AppleScript and improved synchronization. Unfortunately, I can't access Transmit folders anymore.

Update the package and let me know if you find any bugs.

**Comment by nlemoine** [comment]
Just a tiny update: I finally found a (dirty) way to get folders back: https://github.com/nlemoine/transmit-2-ssh-config

It's not 100% reliable but works fine in most cases.
